modules_dir = "artifacts/"

[[module]]
    name = "crypto"
    mem_pages_count = 100
    logger_enabled = true

[[module]]
    name = "ipfsdag"
    mem_pages_count = 100
    logger_enabled = true
    max_heap_size = "1 Gi"

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"
    bash = "/bin/bash"

    [module.wasi]
    # envs = { "/tmp/vault" = "/tmp" }
    preopened_files = ["."]
    mapped_dirs = { "/tmp" = ".", "/tmp/vault" = "./vault" }

[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "./tmp" }

[[module]]
    name = "node"
    mem_pages_count = 100
    logger_enabled = true

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }