modules_dir = "artifacts/"

[[module]]
    name = "crypto"
    mem_pages_count = 100
    logger_enabled = true

[[module]]
    name = "ipfsdag"
    mem_pages_count = 100
    logger_enabled = true
    max_heap_size = "1 Gi"

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"
    bash = "/bin/bash"
    curl = "/usr/bin/curl"

    [module.wasi]
    # envs = { "/tmp/vault" = "/tmp" }
    preopened_files = ["./tmp"]
    mapped_dirs = { "/tmp" = "./tmp", "/tmp/vault" = "./tmp/vault" }

[[module]]
    name = "contract"
    mem_pages_count = 100
    logger_enabled = true
    max_heap_size = "1 Gi"
    
[[module]]
    name = "sqlite3"

    [module.wasi]
    preopened_files = ["./tmp"]
    mapped_dirs = { "tmp" = "./tmp" }

[[module]]
    name = "node"
    mem_pages_count = 100
    logger_enabled = true

    [module.wasi]
    preopened_files = ["./tmp"]
    mapped_dirs = { "tmp" = "./tmp" }